### PR TITLE
Add Sovrin endorser service configurations

### PR DESCRIPTION
**Pull request by WadeBarnes**
This PR builds on https://github.com/bcgov/dts-endorser-service/pull/28

### CODE REVIEW

**Comment by WadeBarnes** [comment]
Ready for review.  Please review and merge https://github.com/bcgov/dts-endorser-service/pull/28 first.

**Comment by WadeBarnes** [comment]
The configurations have already been deployed to `test`, and `prod`.  There is no `dev` environment for Sovrin any longer.  BuilderNet is now used as an internal only network.

The endorsers are not "active" at the moment.  I need to have the DIDs registered with the Sovrin networks to complete the setup.

**Review by esune — APPROVED** [review]

**Comment by esune** [comment]
Leaving the PR open until endorsers are active - @WadeBarnes please close when they are.

**Comment by WadeBarnes** [comment]
I'm going to merge this PR even though the endorsers are not fully active.  I have some other configuration updates that need to happen on all endorsers.

**Pull request merged**
